### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by jelemans** [eunwonki/Volume-Rendering-In-iOS#1]
Can you please explain the data format?
Oh I think I figured it out, 16 bits per pixel and you hard coded the dimensions. Correct?
Thank you!

**Comment by eunwonki** [comment]
Thank you for interesting,  maybe dimension and resolution is hard coded. (I want to change to nrrd format; has a 3d image raw data and header) and now, raw file just has a short(16bit) array value as binary. (CT intensity value range is from -1024 to 3071, head and chest both are CT, mr intensity value range is different maybe)
