### ISSUE TITLE
ZIPFoundation library not working ?

### ISSUE THREAD

**Issue by nghiaphamsg** [eunwonki/Volume-Rendering-In-iOS#2]
Hi eunwonki

Thank you for sharing the repo
I don't kown why `Archive(url:accessMode:)` always returns nil ?
Do you know how to fix this error?

![image](https://user-images.githubusercontent.com/32474027/230422643-13a5afa8-65a0-406c-beb4-901ac1520629.png)

**Comment by eunwonki** [comment]
bro, do you resolve this issue?

**Comment by cyrilzakka** [comment]
Having the same issue: VolumeRendering_iOS/VolumeTexture.swift:54: Fatal error: Unexpectedly found nil while unwrapping an Optional value
